Module2 task1
htmlacademy-adaptive/184172-cat-energy-22 pull request #2
Opened 2021-03-31 02:54 UTC by Torokhov

2021-03-31 14:08 UTC, amaringo requested changes

2021-03-31 14:08 UTC, amaringo commented on source/index.html
> +        <img
🟡 Вместо img лучше сделать пустую обертку, в которой будет лежать гуглояндексовая карта, а фоллбэчить этой картинкой, поставленной на фон.

2021-03-31 14:08 UTC, amaringo commented on source/index.html
> +        <img
🔴 По пункту ТЗ 3.9 название и лого Академии надо сделать ссылкой на лендинг интенсива)

2021-03-31 14:08 UTC, amaringo commented on source/index.html
> +      <div class="socials">
🟡 Тоже можно сделать списком.

2021-03-31 14:08 UTC, amaringo commented on source/index.html
> +          <a class="program-info__link">Каталог SLIM</a>
🔴 Уже можно указать ссылку на страницу каталога, которую создашь потом. Тут по ТЗ должны быть рабочие ссылки.

2021-04-01 02:48 UTC, Torokhov commented on source/index.html
> +        <a class="logo-block__icon" href="#">
удалил href

2021-04-01 02:48 UTC, Torokhov commented on source/index.html
> +        <button class="menu-toggle"></button>
Добавил area-label

2021-04-01 02:49 UTC, Torokhov commented on source/index.html
> +        <p class="how-to-block__text">
переделал на список, добавил модификаторы для иконок

2021-04-01 02:49 UTC, Torokhov commented on source/index.html
> +        <div class="was-now-block">
поправил

2021-04-01 02:50 UTC, Torokhov commented on source/index.html
> +        <img
поправил

2021-04-01 02:50 UTC, Torokhov commented on source/index.html
> +        <img
Пока добавил пустой див, потом подключу карту

2021-04-01 02:50 UTC, Torokhov commented on source/index.html
> +      <div class="socials">
переделал

2021-04-01 02:52 UTC, Torokhov commented on source/index.html
> +          <a class="program-info__link">Каталог SLIM</a>
Добавил ссылки здесь и в навигации

2021-04-01 06:24 UTC, merged