Добавил верстку формы
htmlacademy-adaptive/184172-cat-energy-22 pull request #3
Opened 2021-04-02 03:22 UTC by Torokhov

2021-04-03 02:08 UTC, amaringo requested changes

2021-04-03 02:08 UTC, amaringo commented on source/form.html
> +        <section class="personal-data">
🟡 Группы инпутов в форме семантичнее класть в тег именно для этого и предназначенный - fieldset

2021-04-03 02:08 UTC, amaringo commented on source/form.html
> +              value="Барсик"
🔴 Здесь и далее - не value, а placeholder. Пользователя выбесит везде руками стирать некорректные данные)

2021-04-03 02:08 UTC, amaringo commented on source/form.html
> +          <h2 class="contacts__head">Контактные данные (владельца кота)</h2>
🟡 Если сделаешь филдсетом разделы формы, то для таких имен разделов тоже есть спец. тег - legend

2021-04-03 02:08 UTC, amaringo commented on source/form.html
> +            <label class="form-row__label" for="slim">Сахарозаменитель</label>
🔴  for="sweetener"

2021-04-05 03:21 UTC, Torokhov commented on source/form.html
> +        <h2 class="programm-form__head">
поправил)

2021-04-05 03:25 UTC, Torokhov commented on source/form.html
> +        <section class="personal-data">
заменил на fieldset

2021-04-05 03:25 UTC, Torokhov commented on source/form.html
> +              value="Барсик"
заменил на placeholder

2021-04-05 03:25 UTC, Torokhov commented on source/form.html
> +            <label class="form-row__label" for="slim">Сахарозаменитель</label>
поправил

2021-04-05 12:03 UTC, merged