Module3 task1
htmlacademy-adaptive/184172-cat-energy-22 pull request #5
Opened 2021-04-14 02:13 UTC by Torokhov

2021-04-16 04:29 UTC, amaringo requested changes

2021-04-16 04:29 UTC, amaringo commented on source/sass/example-block.scss
> +  background-color: #eaeaea;
🟡 Все цвета кроме белого и черного стоит положить в переменные

2021-04-16 04:29 UTC, amaringo commented on source/sass/head-block.scss
> +  margin-bottom: 22px;
🔴 Ошибка БЭМ: позиционирование и внешние отступы блоков задаются не в самом блоке, а в том контексте, где он находится. Например, ".main-container .head-block {}" в соответствующем файле. Собственные стили блока должны быть независимыми от контекста.

2021-04-16 04:29 UTC, amaringo commented on source/sass/variables.scss
> +$font-family-base: "Oswald", sans-serif;
🔴 По Б10 надо указать ещё и веб-безопасный шрифт, тот же Ариал

2021-04-16 04:29 UTC, amaringo commented on source/index.html
> +      href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
🔴 По Б9 -  Все нестандартные шрифты должны быть подключены в CSS из папки fonts с помощью правила @font-face

2021-04-20 03:05 UTC, Torokhov commented on source/sass/address.scss
> +  &__text {
Поправил

2021-04-20 03:05 UTC, Torokhov commented on source/sass/base.scss
> +  margin: 0;
отцентрировал

2021-04-20 03:05 UTC, Torokhov commented on source/sass/example-block.scss
> +  padding: 27px 20px 39px 20px;
поправил

2021-04-20 03:05 UTC, Torokhov commented on source/sass/example-block.scss
> +  background-color: #eaeaea;
вынес цвета в переменные

2021-04-20 03:06 UTC, Torokhov commented on source/sass/head-block.scss
> +  margin-bottom: 22px;
поправил

2021-04-20 03:06 UTC, Torokhov commented on source/sass/variables.scss
> +$font-family-base: "Oswald", sans-serif;
поправил

2021-04-20 03:07 UTC, Torokhov commented on source/index.html
> +      href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
подключаю через font-face

2021-04-20 07:25 UTC, merged