Module3 task2
htmlacademy-adaptive/184172-cat-energy-22 pull request #6
Opened 2021-04-29 08:06 UTC by Torokhov

2021-05-04 14:39 UTC, amaringo requested changes

2021-05-04 14:39 UTC, amaringo commented on source/form.html
> +      href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
🔴 Используем локальные шрифты

2021-05-04 14:39 UTC, amaringo commented on source/sass/extra.scss
> +  margin-bottom: 15px;
🔴 Ошибка БЭМ: позиционирование и внешние отступы блоков задаются не в самом блоке, а в том контексте, где он находится.

2021-05-04 14:39 UTC, amaringo commented on source/sass/mixins.scss
> +  border: 1px solid #e7e7e7;
🟡 Можно вынести цвет в переменную

2021-05-04 14:39 UTC, amaringo commented on source/sass/mixins.scss
> +  border: 1px solid #e7e7e7;
🟡 Можно вынести цвет в переменную

2021-05-04 14:39 UTC, amaringo commented on source/sass/personal-data.scss
> +  margin-bottom: 28px;
🔴 Ошибка БЭМ: позиционирование и внешние отступы блоков задаются не в самом блоке, а в том контексте, где он находится.

2021-05-04 14:39 UTC, amaringo commented on source/sass/personal-data.scss
> +  border-bottom: 1px solid #d9d9d9;
🟡 Можно вынести цвет в переменную

2021-05-04 14:39 UTC, amaringo commented on source/sass/program-form.scss
> +  border-top: 1px solid #d9d9d9;
🟡 Можно вынести цвет в переменную

2021-05-04 14:39 UTC, amaringo commented on source/sass/select-program.scss
> +  border-bottom: 1px solid #d9d9d9;
🟡 Можно вынести цвет в переменную

2021-05-04 14:39 UTC, amaringo commented on source/sass/select-program.scss
> +  margin-bottom: 26px;
🔴 Ошибка БЭМ: позиционирование и внешние отступы блоков задаются не в самом блоке, а в том контексте, где он находится.

2021-05-04 14:42 UTC, amaringo requested changes

2021-05-04 14:42 UTC, amaringo commented on source/form.html
>    <head>
🟡 Стоит сделать ссылку на эту страницу с главной - в "Подобрать программу"

2021-05-04 14:44 UTC, amaringo commented on source/form.html
>    <head>
🟡 Логотип на внутренних страницах должен вести на главную.

2021-05-11 07:49 UTC, Torokhov commented on source/form.html
> +      href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
поправил

2021-05-11 07:49 UTC, Torokhov commented on source/sass/extra.scss
> +  margin-bottom: 15px;
Поправил

2021-05-11 07:52 UTC, Torokhov commented on source/sass/select-program.scss
> +  margin-bottom: 26px;
поправил

2021-05-11 07:53 UTC, Torokhov commented on source/sass/mixins.scss
> +  border: 1px solid #e7e7e7;
в цветах прибрался в module3-task3

2021-05-11 23:37 UTC, merged